// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMgFa9QdV-uh3hTBNb53mwTq2CW-uCInY',
    appId: '1:391252002391:web:ced4b5e5469ffe4c140512',
    messagingSenderId: '391252002391',
    projectId: 'smart-study-planner-cs310',
    storageBucket: 'smart-study-planner-cs310.firebasestorage.app',
    authDomain: 'smart-study-planner-cs310.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMgFa9QdV-uh3hTBNb53mwTq2CW-uCInY',
    appId: '1:391252002391:android:ced4b5e5469ffe4c140512',
    messagingSenderId: '391252002391',
    projectId: 'smart-study-planner-cs310',
    storageBucket: 'smart-study-planner-cs310.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7O_ZGaI7-1qI8iM_AALe4PrgC0u0RGHQ',
    appId: '1:391252002391:ios:de24949daaf199ba140512',
    messagingSenderId: '391252002391',
    projectId: 'smart-study-planner-cs310',
    storageBucket: 'smart-study-planner-cs310.firebasestorage.app',
    iosBundleId: 'com.cs310.smartStudyPlanner',
  );
}
